### ISSUE TITLE
Hot Reloading not working properly

### ISSUE THREAD

**Issue by ReactGirl** [ReactGirl/nexter#1]
Issue open in gaearon/react-hot-loader to try to figure it out:
https://github.com/gaearon/react-hot-loader/issues/1141

**Comment by ReactGirl** [comment]
https://github.com/ReactGirl/nexter/blob/master/config/webpack.config.dev.js
https://github.com/ReactGirl/nexter/blob/master/src/components/App.tsx

**Comment by rockchalkwushock** [comment]
The first thing I noticed right away was that you are not using the `react-hot-loader/babel` plugin in the `babel` config. When you ejected CRA it places a `babel` config object in your `package.json`. As you might know already `babel` is what is transpiling your fancy ES6 code down to ES5 for the browsers since not all of the ES6 spec is supported in the browsers at this time. 

Simply insert the following:

```json
{
  "babel": {
     "presets": ["react-app"],
     "plugins": ["react-hot-loader/babel"]
}
```

The next thing I noticed was your import for `hot` was not correct. The below will shore up that problem.

```javascript
import { hot } from 'react-hot-loader/root'
```

Next as per the docs with the latest version of RHL you no longer need to reference `module` so chance your export to the following:

```javascript
// before
export default hot(module)(App)

// after
export default hot(App)
```

I did notice running locally that it does take sometime for the changes to reflect in the browser. This should really be nearly real-time. I think it pertains to the webpack configuration that CRA exposes. I recently had to setup a React + Typescript project from scratch (no CRA) at work and have been planning to write a post on my blog about how to do so with Webpack 4, Babel 7, & RHL. I should have time this weekend to write the post and I will push a repository to GH with the code. If you would like I can comeback and link the post here on this issue for you.

The above changes should set you up moving forward though. 

Cheers! 🍻

**Comment by ReactGirl** [comment]
@rockchalkwushock I will look forward for your post. 
The things that I still notice even after your recommendations is that I still having the same kind of problems than before:

1: No feedback about hot-reloading process in the dev console.
2: "compiling..." Terminal message.
3: As you mentioned, takes sometime to changes to reflect in the browser.

**Comment by rockchalkwushock** [comment]
@ReactGirl 

Yes I forgot to mention that I was not seeing any feedback on the HMR working in the dev console. You should see a basic prompt that says `[WDS] Hot Module Replacement enabled.` and then upon saving a file see a prompt that shows what module was updated:

```text
[HMR]  - ./src/pages/Dashboard.tsx
[HMR] App is up to date.
```

When I finish the post I will link it here for you and should I get a chance tonight I will take another look at the configuration.

**Comment by rockchalkwushock** [comment]
@ReactGirl 

Here are links to the post on my website as well as the code on Github.

https://codybrunner.blog/2019-01-19/building-a-react-project-from-scratch-with-type-script/

https://github.com/rockchalkwushock/react-typescript-from-scratch

Cheers 🍻
